"""rebuild_billboard_migrations

Revision ID: af8a8b3c33d5
Revises: e69999560f4f
Create Date: 2025-12-10 02:39:29.265363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8a8b3c33d5'
down_revision: Union[str, None] = 'e69999560f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billboard_code', sa.String(length=100), nullable=False),
    sa.Column('billboard_type', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height_from_ground', sa.Float(), nullable=True),
    sa.Column('loop_timing', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_indoor', sa.String(length=10), nullable=False),
    sa.Column('azimuth_from_north', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('media_owner_name', sa.String(length=255), nullable=False),
    sa.Column('network_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billboard_billboard_code'), 'billboard', ['billboard_code'], unique=True)
    op.create_index(op.f('ix_billboard_id'), 'billboard', ['id'], unique=False)
    op.create_table('geo_filter_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('division_id', sa.String(length=36), nullable=False),
    sa.Column('division_name_en', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_filter_data_country_code'), 'geo_filter_data', ['country_code'], unique=False)
    op.create_index(op.f('ix_geo_filter_data_division_id'), 'geo_filter_data', ['division_id'], unique=True)
    op.create_index(op.f('ix_geo_filter_data_id'), 'geo_filter_data', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('time_unit', sa.String(length=20), nullable=False),
    sa.Column('week_1st', sa.String(length=50), nullable=True),
    sa.Column('selected_dates', sa.JSON(), nullable=True),
    sa.Column('kpi_start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('kpi_end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('hour_range', sa.JSON(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('cities', sa.JSON(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('age_groups', sa.JSON(), nullable=False),
    sa.Column('spc_category', sa.String(length=50), nullable=True),
    sa.Column('mobility_modes', sa.JSON(), nullable=False),
    sa.Column('poi_categories', sa.JSON(), nullable=False),
    sa.Column('billboard_ids', sa.JSON(), nullable=False),
    sa.Column('inventory_ids', sa.JSON(), nullable=False),
    sa.Column('billboards_tree', sa.JSON(), nullable=True),
    sa.Column('billboard_kpi_data', sa.JSON(), nullable=True),
    sa.Column('kpi_data', sa.JSON(), nullable=True),
    sa.Column('kpi_full_data', sa.JSON(), nullable=True),
    sa.Column('audience_breakdown', sa.JSON(), nullable=True),
    sa.Column('customize_kpis', sa.JSON(), nullable=True),
    sa.Column('operator_first_name', sa.String(length=100), nullable=True),
    sa.Column('operator_last_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.add_column('admins', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('organization_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'organization_type')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'phone')
    op.drop_column('admins', 'phone')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_geo_filter_data_id'), table_name='geo_filter_data')
    op.drop_index(op.f('ix_geo_filter_data_division_id'), table_name='geo_filter_data')
    op.drop_index(op.f('ix_geo_filter_data_country_code'), table_name='geo_filter_data')
    op.drop_table('geo_filter_data')
    op.drop_index(op.f('ix_billboard_id'), table_name='billboard')
    op.drop_index(op.f('ix_billboard_billboard_code'), table_name='billboard')
    op.drop_table('billboard')
    # ### end Alembic commands ###
